### ISSUE TITLE
Request to release the latest package to pip

### ISSUE THREAD

**Issue by boslbosl** [maztohir/bigquery-sql-parser#5]
Hi, Muhamad 
I'm finding a bigquery script parser, I guess the script module in this project provides what I want exactly.
But the script module doesn't seem to be released to pip, so I couldn't include it to my project easily.
Could you kindly release the latest package to pip. I will be helpful for me!

Thanks in advance!!

**Comment by maztohir** [comment]
Hi, thanks for raising this issues, I've tried to upload it on PyPI here https://pypi.org/project/bigquery-sql-parser/
Feel free to contribute as well on this and add some more features as needed.

Thanks a ton!
